# Program without exception
try:
    a = 10
    print("Value of x:",a)

except:
    print("An exception occured")

# Program with exception
try:
    print("Value of x:",a)

except:
    print("An exception occured")